//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus.Tools.Validations.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Tools.Validations.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This field does not contain a valid CNPJ..
        /// </summary>
        public static string CnpjValidation {
            get {
                return ResourceManager.GetString("CnpjValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The field must contain a value equal to &apos;{0}&apos;..
        /// </summary>
        public static string CompareValidation {
            get {
                return ResourceManager.GetString("CompareValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This field does not contain a valid CPF..
        /// </summary>
        public static string ContainsValidation {
            get {
                return ResourceManager.GetString("ContainsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This field does not contain a valid CPF or CNPJ..
        /// </summary>
        public static string CpfOrCnpjValidation {
            get {
                return ResourceManager.GetString("CpfOrCnpjValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This field does not contain a valid CPF..
        /// </summary>
        public static string CpfValidation {
            get {
                return ResourceManager.GetString("CpfValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value of this field does not match a valid email..
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The difference between the current date and the chosen date must be at least {0} years..
        /// </summary>
        public static string MinYearsLestedsValidation {
            get {
                return ResourceManager.GetString("MinYearsLestedsValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This field does not contain one Name..
        /// </summary>
        public static string NameValidation {
            get {
                return ResourceManager.GetString("NameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A password must contain a number, a lowercase letter, a capital letter and a special character..
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The field must be a valid phone number..
        /// </summary>
        public static string PhoneValidation {
            get {
                return ResourceManager.GetString("PhoneValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The field is required..
        /// </summary>
        public static string RequiredValidation {
            get {
                return ResourceManager.GetString("RequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The string must contain at least &apos;{1}&apos; characters..
        /// </summary>
        public static string SmallStringLengthValidation {
            get {
                return ResourceManager.GetString("SmallStringLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The string should not contain more than &apos;{0}&apos; characters..
        /// </summary>
        public static string StringLengthValidation {
            get {
                return ResourceManager.GetString("StringLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This value is not and a time use the format: 00:00:00.
        /// </summary>
        public static string TimeSpanValidation {
            get {
                return ResourceManager.GetString("TimeSpanValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a There is already a registration using this value..
        /// </summary>
        public static string UniqueInDatabaseValidation {
            get {
                return ResourceManager.GetString("UniqueInDatabaseValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The &apos;{0}&apos; field is not a valid ZIP Code..
        /// </summary>
        public static string ZipCodeValidation {
            get {
                return ResourceManager.GetString("ZipCodeValidation", resourceCulture);
            }
        }
    }
}
